package frontend;

/**
 * Created by stalker on 13.02.16.
 */

public enum UserState {
    SLEEPS,

    PENDING_AUTHORIZED,
    PENDING_REGISTRATION,
    PENDING_LEAVING,

    SUCCESSFUL_AUTHORIZED,
    SUCCESSFUL_REGISTERED,
    SUCCESSFUL_LEAVING,

    UNSUCCESSFUL_AUTHORIZED,
    UNSUCCESSFUL_REGISTERED,
    UNSUCCESSFUL_LEAVING
}